# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Build_Status',
        ),
        migrations.RenameField(
            model_name='build_status',
            old_name='question_text',
            new_name='status_txt',
        ),
    ]
